
#server
server:
  port: 8080
  servlet:
    context-path: /


#spring
spring:
  datasource:
    url: jdbc:mysql:///pensionsystem?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: true
  resources:
    static-locations: file:F:\pension_system
  mvc:
    static-path-pattern: /**
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/mysql/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG

#spring thread pool
async-thread-pool:
  corePoolSize: 20
  maxPoolSize: 1000
  keepAliveSeconds: 30
  queueCapacity: 1000


           